baseurl = "/"
languageCode = "en-gb"
languageLang = "en"
title = "Craig Baldwin"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  siteTitle = "Craig Baldwin [dot] com"
  tagline = "Front-end developer"

[menu]
  [[menu.main]]
    identifier = "about"
    title = "About"
    pre = "ðŸ˜¶"
    post = "Craig"
    url = "/about/"
    weight = -100

  [[menu.main]]
    identifier = "work"
    title = "Work"
    pre = "ðŸ’»"
    post = "Showcase"
    url = "/work/"
    weight = -75

  [[menu.main]]
    identifier = "mountains"
    title = "Mountains"
    pre = "ðŸ—»"
    post = "+ Lakes"
    url = "/mountains/"
    weight = -50

  [[menu.main]]
    identifier = "contact"
    title = "Contact"
    pre = "ðŸ“§"
    post = "+ Social"
    url = "/contact/"
    weight = -25