baseurl = "/"
languageCode = "en-gb"
languageLang = "en"
title = "Craig Baldwin"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  siteTitle = "Craig Baldwin [dot] com"
  tagline = "Front-end developer"

[menu]
  [[menu.main]]
    identifier = "home"
    title = "Home"
    pre = "ğŸ¡"
    post = "Start again"
    url = "/"
    weight = -125

  [[menu.main]]
    identifier = "about"
    title = "About"
    pre = "ğŸ‘‹"
    post = "Craig"
    url = "/about/"
    weight = -100

  [[menu.main]]
    identifier = "work"
    title = "Work"
    pre = "ğŸ’»"
    post = "Showcase"
    url = "/work/"
    weight = -75

  [[menu.main]]
    identifier = "stats"
    title = "Stats"
    pre = "ğŸ“Š"
    post = "+ Mountains"
    url = "/stats/"
    weight = -50

  [[menu.main]]
    identifier = "contact"
    title = "Contact"
    pre = "ğŸ“«"
    post = "+ Social"
    url = "/contact/"
    weight = -25

  [[menu.footer]]
    identifier = "info"
    title = "Info"
    url = "/about/info/"
    weight = -50

  [[menu.footer]]
    identifier = "repo"
    title = "Repo"
    url = "https://github.com/csbrightside/craigbaldwin.com"
    weight = -25
